// Code generated by protoc-gen-go.
// source: spec/runner.proto
// DO NOT EDIT!

package spec

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// The run command
type RunCommand struct {
	// ID
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// Name
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// (Command) arguments
	Args []string `protobuf:"bytes,3,rep,name=args" json:"args,omitempty"`
	// Workdir
	Workdir string `protobuf:"bytes,4,opt,name=workdir" json:"workdir,omitempty"`
	// Environment variables
	Envs []string `protobuf:"bytes,5,rep,name=envs" json:"envs,omitempty"`
}

func (m *RunCommand) Reset()                    { *m = RunCommand{} }
func (m *RunCommand) String() string            { return proto.CompactTextString(m) }
func (*RunCommand) ProtoMessage()               {}
func (*RunCommand) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *RunCommand) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RunCommand) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RunCommand) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *RunCommand) GetWorkdir() string {
	if m != nil {
		return m.Workdir
	}
	return ""
}

func (m *RunCommand) GetEnvs() []string {
	if m != nil {
		return m.Envs
	}
	return nil
}

// The running process
type RunProcess struct {
	// The id
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// Process state
	State *RunProcessState `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	// The run command of this process
	Command *RunCommand `protobuf:"bytes,3,opt,name=command" json:"command,omitempty"`
	// The log
	Log *RunProcessLog `protobuf:"bytes,4,opt,name=log" json:"log,omitempty"`
}

func (m *RunProcess) Reset()                    { *m = RunProcess{} }
func (m *RunProcess) String() string            { return proto.CompactTextString(m) }
func (*RunProcess) ProtoMessage()               {}
func (*RunProcess) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *RunProcess) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RunProcess) GetState() *RunProcessState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *RunProcess) GetCommand() *RunCommand {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *RunProcess) GetLog() *RunProcessLog {
	if m != nil {
		return m.Log
	}
	return nil
}

// State of run process
type RunProcessState struct {
	// The pid
	Pid int32 `protobuf:"varint,1,opt,name=pid" json:"pid,omitempty"`
	// The workdir (absolute path)
	Workdir string `protobuf:"bytes,3,opt,name=workdir" json:"workdir,omitempty"`
	// The start time
	StartTime *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=startTime" json:"startTime,omitempty"`
}

func (m *RunProcessState) Reset()                    { *m = RunProcessState{} }
func (m *RunProcessState) String() string            { return proto.CompactTextString(m) }
func (*RunProcessState) ProtoMessage()               {}
func (*RunProcessState) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *RunProcessState) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *RunProcessState) GetWorkdir() string {
	if m != nil {
		return m.Workdir
	}
	return ""
}

func (m *RunProcessState) GetStartTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

// Run process log
type RunProcessLog struct {
	// Stdout log
	Stdout string `protobuf:"bytes,1,opt,name=stdout" json:"stdout,omitempty"`
	// Stderr log
	Stderr string `protobuf:"bytes,2,opt,name=stderr" json:"stderr,omitempty"`
}

func (m *RunProcessLog) Reset()                    { *m = RunProcessLog{} }
func (m *RunProcessLog) String() string            { return proto.CompactTextString(m) }
func (*RunProcessLog) ProtoMessage()               {}
func (*RunProcessLog) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *RunProcessLog) GetStdout() string {
	if m != nil {
		return m.Stdout
	}
	return ""
}

func (m *RunProcessLog) GetStderr() string {
	if m != nil {
		return m.Stderr
	}
	return ""
}

func init() {
	proto.RegisterType((*RunCommand)(nil), "openlight.spec.RunCommand")
	proto.RegisterType((*RunProcess)(nil), "openlight.spec.RunProcess")
	proto.RegisterType((*RunProcessState)(nil), "openlight.spec.RunProcessState")
	proto.RegisterType((*RunProcessLog)(nil), "openlight.spec.RunProcessLog")
}

func init() { proto.RegisterFile("spec/runner.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x4f, 0xe3, 0x30,
	0x10, 0x55, 0x9a, 0x7e, 0xa8, 0x53, 0x6d, 0x77, 0xd7, 0x87, 0x95, 0xb7, 0x12, 0x6a, 0x95, 0x13,
	0x27, 0x07, 0x15, 0x90, 0xb8, 0x21, 0x95, 0x2b, 0x87, 0xca, 0xf4, 0xc4, 0x2d, 0x4d, 0x8c, 0x6b,
	0x51, 0xdb, 0x91, 0xed, 0xd0, 0xff, 0xc6, 0xaf, 0x43, 0x76, 0x1c, 0x95, 0x16, 0xb8, 0xcd, 0x3c,
	0xbf, 0xd1, 0x7b, 0x6f, 0xc6, 0xf0, 0xd7, 0xd6, 0xac, 0xcc, 0x4d, 0xa3, 0x14, 0x33, 0xa4, 0x36,
	0xda, 0x69, 0x34, 0xd5, 0x35, 0x53, 0x7b, 0xc1, 0x77, 0x8e, 0xf8, 0xc7, 0xd9, 0x9c, 0x6b, 0xcd,
	0xf7, 0x2c, 0x0f, 0xaf, 0xdb, 0xe6, 0x25, 0x77, 0x42, 0x32, 0xeb, 0x0a, 0x59, 0xb7, 0x03, 0x99,
	0x01, 0xa0, 0x8d, 0x7a, 0xd0, 0x52, 0x16, 0xaa, 0x42, 0x53, 0xe8, 0x89, 0x0a, 0x27, 0x8b, 0xe4,
	0x72, 0x4c, 0x7b, 0xa2, 0x42, 0x08, 0xfa, 0xaa, 0x90, 0x0c, 0xf7, 0x02, 0x12, 0x6a, 0x8f, 0x15,
	0x86, 0x5b, 0x9c, 0x2e, 0x52, 0x8f, 0xf9, 0x1a, 0x61, 0x18, 0x1d, 0xb4, 0x79, 0xad, 0x84, 0xc1,
	0xfd, 0x40, 0xed, 0x5a, 0xcf, 0x66, 0xea, 0xcd, 0xe2, 0x41, 0xcb, 0xf6, 0x75, 0xf6, 0x9e, 0x04,
	0xd1, 0xb5, 0xd1, 0x25, 0xb3, 0xf6, 0x8b, 0xe8, 0x2d, 0x0c, 0xac, 0x2b, 0x5c, 0xab, 0x3a, 0x59,
	0xce, 0xc9, 0x69, 0x26, 0x72, 0x1c, 0x7d, 0xf2, 0x34, 0xda, 0xb2, 0xd1, 0x0d, 0x8c, 0xca, 0x36,
	0x06, 0x4e, 0xc3, 0xe0, 0xec, 0x9b, 0xc1, 0x18, 0x94, 0x76, 0x54, 0x94, 0x43, 0xba, 0xd7, 0x3c,
	0xb8, 0x9e, 0x2c, 0x2f, 0x7e, 0x96, 0x7a, 0xd4, 0x9c, 0x7a, 0x66, 0x76, 0x80, 0xdf, 0x67, 0x06,
	0xd0, 0x1f, 0x48, 0xeb, 0x98, 0x60, 0x40, 0x7d, 0xf9, 0x79, 0x1f, 0xe9, 0xe9, 0x3e, 0xee, 0x60,
	0x6c, 0x5d, 0x61, 0xdc, 0x46, 0x48, 0x16, 0x55, 0x67, 0xa4, 0x3d, 0x12, 0xe9, 0x8e, 0x44, 0x36,
	0xdd, 0x91, 0xe8, 0x91, 0x9c, 0xdd, 0xc3, 0xaf, 0x13, 0x3b, 0xe8, 0x1f, 0x0c, 0xad, 0xab, 0x74,
	0xe3, 0xe2, 0xee, 0x62, 0x17, 0x71, 0x66, 0x4c, 0x3c, 0x5b, 0xec, 0x56, 0x57, 0xf0, 0xbf, 0xd4,
	0x92, 0x70, 0xe1, 0x76, 0xcd, 0xf6, 0x2c, 0xe9, 0x6a, 0x42, 0xc3, 0x37, 0x5a, 0x7b, 0x0b, 0xeb,
	0xe4, 0xb9, 0xef, 0xc1, 0xed, 0x30, 0x38, 0xba, 0xfe, 0x08, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x97,
	0x5c, 0xd6, 0x69, 0x02, 0x00, 0x00,
}
